#!/bin/bash
echo """
DOCKER_PASS=\"$DOCKER_PASS\"

DOCKER_USER=\"$DOCKER_USER\"

KEYCLOAK_OUTBOX_CLIENT_SECRET=\"$KEYCLOAK_OUTBOX_CLIENT_SECRET\"

OUTBOX_USER_NAME=\"$OUTBOX_USER_NAME\"

OUTBOX_USER_PASS=\"$OUTBOX_USER_PASS\"

MONGO_AUTH=\"$MONGO_AUTH\"

MONGO_DB=\"$MONGO_DB\"

MONGO_DB_TEST=\"$MONGO_DB_TEST\"

MONGO_HOST_TEST=\"$MONGO_HOST_TEST\"

MONGO_HOST=\"$MONGO_HOST\"

MONGO_PASS=\"$MONGO_PASS\"

MONGO_USER=\"$MONGO_USER\"

MONGO_HOST_PERMISSIONS_TEST=\"$MONGO_HOST_PERMISSIONS_TEST\"

MONGO_HOST_PERMISSIONS=\"$MONGO_HOST_PERMISSIONS\"

MONGO_DB_PERMISSIONS=\"$MONGO_DB_PERMISSIONS\"

MONGO_DB_PERMISSIONS_TEST=\"$MONGO_DB_PERMISSIONS_TEST\"

MONGO_USER_PERMISSIONS=\"$MONGO_USER_PERMISSIONS\"

MONGO_PASS_PERMISSIONS=\"$MONGO_PASS_PERMISSIONS\"

MONGO_AUTH_PERMISSIONS=\"$MONGO_AUTH_PERMISSIONS\"
"""
